-- transactions: the core ledger. Replaces the old `expenses` table.
-- Supports income, expense, and transfer. Sign convention: amount > 0 always;
-- direction comes from `kind`. Transfers reference a sibling row via transfer_pair_id.

create table public.transactions (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users(id) on delete cascade,
  account_id        uuid not null references public.accounts(id) on delete restrict,
  category_id       uuid references public.categories(id) on delete set null,
  amount            numeric(14,2) not null check (amount >= 0),
  kind              text not null check (kind in ('expense','income','transfer')),
  currency          char(3) not null,
  occurred_on       date not null,
  note              text,
  -- Mobile sync support
  client_uuid       uuid,
  transfer_pair_id  uuid references public.transactions(id) on delete set null,
  deleted_at        timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (user_id, client_uuid)
);

comment on table public.transactions is
  'Core ledger. Income/expense/transfer. amount always positive; direction from kind. Soft-deleted via deleted_at for sync.';
comment on column public.transactions.client_uuid is
  'Idempotency key generated by the mobile client. Lets retries hit the same row instead of duplicating.';
comment on column public.transactions.transfer_pair_id is
  'For kind=transfer, points to the matching row on the other account.';

-- Hot-path indexes
create index transactions_user_date_idx
  on public.transactions (user_id, occurred_on desc);

create index transactions_user_category_idx
  on public.transactions (user_id, category_id);

create index transactions_user_active_idx
  on public.transactions (user_id, occurred_on desc)
  where deleted_at is null;

-- Delta-sync index: clients fetch rows changed since last sync.
create index transactions_user_updated_idx
  on public.transactions (user_id, updated_at desc);

create trigger transactions_set_updated_at
  before update on public.transactions
  for each row execute function public.set_updated_at();
